### ISSUE TITLE
Next button doesn't work

### ISSUE THREAD

**Issue by lucasharada** [surveyjs/surveyjs_react_quickstart#9] opened 2018-11-15 21:22 UTC
I tried copying all the code from this quickstart (`v1.0.55`), but even though the survey appears and the callback passed to `onValueChanged` works properly, I can't manage to go to the next page.

Whenever I click the button, it does all validation, but it stops there.

Related code:

```
import * as Survey from 'survey-react';
import 'survey-react/survey.css';

[...]
render() {
    const { processing, assessment } = this.props;
    if (isEmpty(assessment)) return null;

    const {
      fields: { assessment: assessmentObject },
    } = assessment.items[0];

    const model = new Survey.Model(JSON.parse(assessmentObject.json));
    console.log(JSON.parse(assessmentObject.json));

    return (
      <div>
        <Helmet>
          <title>Survey Test</title>
          <meta name="description" content="Survey Test" />
        </Helmet>
        <AppContainer>
          <LoadingOverlay show={processing} />
          <Grid item xs={12}>
            <Header data={assessment} />
          </Grid>
          <Grid item xs={12}>
            <div className="surveyjs">
              <Survey.Survey
                model={model}
                onComplete={this.onComplete}
                onValueChanged={this.onValueChanged}
              />
            </div>
          </Grid>
        </AppContainer>
      </div>
    );
  }
```

**Comment by lucasharada** [comment] 2018-11-15 21:39
Got to work using version`1.0.53`.

**Comment by dmitrykurmanov** [comment] 2018-11-16 08:38
@lucasharada hello, thank you for the reporting. Could you please provide a json to reproduce the problem? The code you've provided above doesn't help with reproducing I think.


_duplicate of https://github.com/surveyjs/surveyjs/issues/1437_

**Closed** 2018-11-16 13:30 UTC
Labels: duplicate
